const types = {
    GET_BOOKS: 'GET_BOOKS',
    CREATE_BOOK: 'CREATE_BOOK',
    EDIT_BOOK: 'EDIT_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',

    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    LOGIN_START: "LOGIN_START",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT_START: "LOGOUT_START",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    GET_SHELF: "GET_SHELF",
    ADD_TO_SHELF: "ADD_TO_SHELF",
    REMOVE_FROM_SHELF: "REMOVE_FROM_SHELF",

    GET_HISTORY: "GET_HISTORY",
    ADD_TO_HISTORY: "ADD_TO_HISTORY",

    GET_FAVORITES: 'GET_FAVORITES',
    ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
    REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES'
};

export default types;